[package]
name = "reverso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
md-5 = "0.10"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
