[tasks.install]
command = "sudo"
args = [
    "cp",
    "target/release/${CARGO_MAKE_CRATE_FS_NAME}",
    "/usr/bin"
]
dependencies = ["build-release"]

[tasks.install-debug]
command = "sudo"
args = [
    "cp",
    "target/debug/${CARGO_MAKE_CRATE_FS_NAME}",
    "/usr/bin"
]
dependencies = ["build"]
